#ifndef MLIR_DIALECT_Presburger_PresburgerOPS_H
#define MLIR_DIALECT_Presburger_PresburgerOPS_H

#include "mlir/Dialect/Presburger/Attributes.h"
#include "mlir/Dialect/Presburger/Types.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/Operation.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"

namespace mlir {

namespace OpTrait {
/// A trait that marks an operation that produces PresburgerSets
/// Note: apparently traits can only be defined in this namespace
template <typename ConcreteType>
class ProducesPresburgerSet
    : public TraitBase<ConcreteType, ProducesPresburgerSet> {
public:
  static LogicalResult verifyTrait(Operation *op) {
    for (auto resultType : op->getResultTypes())
      if (resultType.isa<presburger::PresburgerSetType>())
        return success();
    return failure();
  }
};
} // namespace OpTrait
namespace presburger {

/// Retrieve the class declarations generated by TableGen
#define GET_OP_CLASSES
#include "mlir/Dialect/Presburger/PresburgerOps.h.inc"

} // namespace presburger
} // namespace mlir

#endif // MLIR_DIALECT_Presburger_PresburgerOPS_H
