#ifndef MLIR_DIALECT_Presburger_PresburgerOPS_H
#define MLIR_DIALECT_Presburger_PresburgerOPS_H

#include "mlir/Dialect/Presburger/Attributes.h"
#include "mlir/Dialect/Presburger/Types.h"
#include "mlir/Interfaces/SideEffects.h"

namespace mlir {
namespace presburger {

/// Retrieve the class declarations generated by TableGen
#define GET_OP_CLASSES
#include "mlir/Dialect/Presburger/PresburgerOps.h.inc"

} // namespace presburger
} // namespace mlir

#endif // MLIR_DIALECT_Presburger_PresburgerOPS_H
